import "./globals.css";
import Sidebar from "../../Componets/Layout/Sidebar";
import { Search, Bell, CircleUserRound } from "lucide-react";
import { Inter, Poppins } from "next/font/google";
import SidebarModal from "../../Componets/Modals/SidebarModal";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const inter = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Oaza Mira",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/logo.png", sizes: "32x32" }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`$  antialiased`}>
        <div className="flex  bg-[#FAFAFA]    ">
          {/* Sidebar */}
          <Sidebar />

          {/* Main content */}
          <div className="flex-1 flex flex-col min-h-screen ">
            {/* Topbar */}
            <div className="flex flex-col md:flex-row md:justify-between md:items-center gap-3 p-3 mt-2 mx-3 bg-white rounded-[31px] h-auto">
              <div className="relative w-full md:w-1/2 flex items-center gap-4">
                {/* Menu icon */}

                <div className="relative w-full bg-white rounded-[31px]">
                  <input
                    type="text"
                    placeholder="Search..."
                    className=" w-full pl-10 pr-4 py-2 bg-[#EBEBEB] rounded-[31px] text-sm placeholder:text-[#212121] placeholder:text-sm"
                  />

                  <div className="absolute left-3 top-1/2 transform -translate-y-1/2 pointer-events-none">
                    <Search size={16} color="#586A84" />
                  </div>
                </div>
              </div>

              {/* icons */}
              <div className="flex justify-end gap-x-4 md:gap-x-6 md:pr-3">
                <div className="md:hidden absolute top-14 left-4 z-50">
                  <SidebarModal />
                </div>
                <Bell color="#6C8B48" height={20} width={20} />
                <CircleUserRound color="#6C8B48" height={20} width={20} />
              </div>
            </div>

            {/* Page content */}
            <main
              className={`p-2 ${poppins.className} ${inter.className} min-h-screen `}
            >
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
